### ISSUE TITLE
App crash Android

### ISSUE THREAD

**Issue by ckarmy** [fuse-open/fuselibs#1249]
With the las version my app on Android crash when I open it with this log:

```
Running logcat on 315a415141563098

01-15 16:20:37.180  8918  8918 E Zygote  : isWhitelistProcess - Process is Whitelisted
01-15 16:20:37.180  8918  8918 E libpersona: scanKnoxPersonas
01-15 16:20:37.180  8918  8918 E libpersona: Couldn't open the File - /data/system/users/0/personalist.xml - No such file or directory
01-15 16:20:37.181  8918  8918 W SELinux : SELinux selinux_android_compute_policy_index : Policy Index[2],  Con:u:r:zygote:s0 RAM:SEPF_SM-G9650_8.0.0_0017, [-1 -1 -1 -1 0 1]
01-15 16:20:37.181  8918  8918 I SELinux : SELinux: seapp_context_lookup: seinfo=untrusted, level=s0:c512,c768, pkgname=com.goodfactory.wali
01-15 16:20:37.182  1428  2234 I ActivityManager: Start proc 8918:com.goodfactory.wali/u0a571 for activity com.goodfactory.wali/.wali
01-15 16:20:37.183  8918  8918 I zygote  : Late-enabling -Xcheck:jni
01-15 16:20:37.197  8918  8918 W zygote  : Using default instruction set features for ARM CPU variant (cortex-a9) using conservative defaults
01-15 16:20:37.211  8918  8918 D TimaKeyStoreProvider: TimaKeyStore is not enabled: cannot add TimaSignature Service and generateKeyPair Service
01-15 16:20:37.211  8918  8918 D ActivityThread: Added TimaKeyStore provider
01-15 16:20:37.257  8918  8918 D FirebaseApp: com.google.firebase.auth.FirebaseAuth is not linked. Skipping initialization.
01-15 16:20:37.266  8918  8918 D FirebaseApp: com.google.firebase.crash.FirebaseCrash is not linked. Skipping initialization.
01-15 16:20:37.269  8918  8918 I FirebaseInitProvider: FirebaseApp initialization successful
01-15 16:20:37.278  1428  2234 D SamsungAlarmManager: Cancel Alarm calling from uid:10571 pid :8918 / op:PendingIntent{ed81f9d: PendingIntentRecord{c157c12 com.goodfactory.wali broadcastIntent}}
01-15 16:20:37.321  8918  8954 I FA      : App measurement is starting up, version: 12211
01-15 16:20:37.321  8918  8954 I FA      : To enable debug logging run: adb shell setprop log.tag.FA VERBOSE
01-15 16:20:37.321  8918  8954 I FA      : To enable faster debug mode event logging run:
01-15 16:20:37.321  8918  8954 I FA      :   adb shell setprop debug.firebase.analytics.app com.goodfactory.wali
01-15 16:20:37.336  8918  8918 D wali    : SDK: 26
01-15 16:20:37.378  8918  8918 I Adreno  : QUALCOMM build                   : fa5d0e7, I788affba20
01-15 16:20:37.378  8918  8918 I Adreno  : Build Date                       : 06/12/18
01-15 16:20:37.378  8918  8918 I Adreno  : OpenGL ES Shader Compiler Version: EV031.22.00.02_ESPL1
01-15 16:20:37.378  8918  8918 I Adreno  : Local Branch                     :
01-15 16:20:37.378  8918  8918 I Adreno  : Remote Branch                    : refs/tags/AU_LINUX_ANDROID_LA.UM.6.3.C1.08.00.00.432.044
01-15 16:20:37.378  8918  8918 I Adreno  : Remote Branch                    : NONE
01-15 16:20:37.378  8918  8918 I Adreno  : Reconstruct Branch               : NOTHING
01-15 16:20:37.383  8918  8918 I Adreno  : PFP: 0x016ee155, ME: 0x00000000
01-15 16:20:37.392  8918  8918 V Surface : sf_framedrop debug : 0x4f4c, game : false, logging : 0
01-15 16:20:37.489  8918  8930 I zygote  : Do partial code cache collection, code=30KB, data=19KB
01-15 16:20:37.489  8918  8930 I zygote  : After code cache collection, code=30KB, data=19KB
01-15 16:20:37.489  8918  8930 I zygote  : Increasing code cache capacity to 128KB
01-15 16:20:37.510  8918  8918 W Bundle  : Key _fbSourceApplicationHasBeenSet expected String but value was a java.lang.Boolean.  The default value <null> was returned.
01-15 16:20:37.511  8918  8918 W Bundle  : Attempt to cast generated internal exception:
01-15 16:20:37.511  8918  8918 W Bundle  : java.lang.ClassCastException: java.lang.Boolean cannot be cast to java.lang.String
01-15 16:20:37.511  8918  8918 W Bundle  : 	at android.os.BaseBundle.getString(BaseBundle.java:1089)
01-15 16:20:37.511  8918  8918 W Bundle  : 	at com.fuse.firebase.Notifications.PushNotificationReceiver.ToJsonString(PushNotificationReceiver.java:63)
01-15 16:20:37.511  8918  8918 W Bundle  : 	at com.foreign.Firebase.Notifications.AndroidImpl$1.onIntent(AndroidImpl.java:44)
01-15 16:20:37.511  8918  8918 W Bundle  : 	at com.fuse.Activity._dispatchToListeners(Activity.java:112)
01-15 16:20:37.511  8918  8918 W Bundle  : 	at com.fuse.Activity._dispatchUnhandledToListeners(Activity.java:99)
01-15 16:20:37.511  8918  8918 W Bundle  : 	at com.fuse.Activity.subscribeToIntents(Activity.java:75)
01-15 16:20:37.511  8918  8918 W Bundle  : 	at com.foreign.Firebase.Notifications.AndroidImpl.JInit429(AndroidImpl.java:41)
01-15 16:20:37.511  8918  8918 W Bundle  : 	at com.Bindings.ExternedBlockHost.JInit429(ExternedBlockHost.java:2015)
01-15 16:20:37.511  8918  8918 W Bundle  : 	at com.fuse.ActivityNativeEntryPoints.cppOnCreate(Native Method)
01-15 16:20:37.511  8918  8918 W Bundle  : 	at com.fuse.App.onCreate(App.java:90)
01-15 16:20:37.511  8918  8918 W Bundle  : 	at com.goodfactory.wali.wali.onCreate(wali.java:54)
01-15 16:20:37.511  8918  8918 W Bundle  : 	at android.app.Activity.performCreate(Activity.java:7183)
01-15 16:20:37.511  8918  8918 W Bundle  : 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1220)
01-15 16:20:37.511  8918  8918 W Bundle  : 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2908)
01-15 16:20:37.511  8918  8918 W Bundle  : 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3030)
01-15 16:20:37.511  8918  8918 W Bundle  : 	at android.app.ActivityThread.-wrap11(Unknown Source:0)
01-15 16:20:37.511  8918  8918 W Bundle  : 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696)
01-15 16:20:37.511  8918  8918 W Bundle  : 	at android.os.Handler.dispatchMessage(Handler.java:105)
01-15 16:20:37.511  8918  8918 W Bundle  : 	at android.os.Looper.loop(Looper.java:164)
01-15 16:20:37.511  8918  8918 W Bundle  : 	at android.app.ActivityThread.main(ActivityThread.java:6938)
01-15 16:20:37.511  8918  8918 W Bundle  : 	at java.lang.reflect.Method.invoke(Native Method)
01-15 16:20:37.511  8918  8918 W Bundle  : 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
01-15 16:20:37.511  8918  8918 W Bundle  : 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
01-15 16:20:37.511  8918  8918 W Bundle  : Key _fbSourceApplicationHasBeenSet expected String but value was a java.lang.Boolean.  The default value <null> was returned.
01-15 16:20:37.511  8918  8918 W Bundle  : Attempt to cast generated internal exception:
01-15 16:20:37.511  8918  8918 W Bundle  : java.lang.ClassCastException: java.lang.Boolean cannot be cast to java.lang.String
01-15 16:20:37.511  8918  8918 W Bundle  : 	at android.os.BaseBundle.getString(BaseBundle.java:1089)
01-15 16:20:37.511  8918  8918 W Bundle  : 	at com.fuse.firebase.Notifications.PushNotificationReceiver.ToJsonString(PushNotificationReceiver.java:67)
01-15 16:20:37.511  8918  8918 W Bundle  : 	at com.foreign.Firebase.Notifications.AndroidImpl$1.onIntent(AndroidImpl.java:44)
01-15 16:20:37.511  8918  8918 W Bundle  : 	at com.fuse.Activity._dispatchToListeners(Activity.java:112)
01-15 16:20:37.511  8918  8918 W Bundle  : 	at com.fuse.Activity._dispatchUnhandledToListeners(Activity.java:99)
01-15 16:20:37.511  8918  8918 W Bundle  : 	at com.fuse.Activity.subscribeToIntents(Activity.java:75)
01-15 16:20:37.511  8918  8918 W Bundle  : 	at com.foreign.Firebase.Notifications.AndroidImpl.JInit429(AndroidImpl.java:41)
01-15 16:20:37.511  8918  8918 W Bundle  : 	at com.Bindings.ExternedBlockHost.JInit429(ExternedBlockHost.java:2015)
01-15 16:20:37.511  8918  8918 W Bundle  : 	at com.fuse.ActivityNativeEntryPoints.cppOnCreate(Native Method)
01-15 16:20:37.511  8918  8918 W Bundle  : 	at com.fuse.App.onCreate(App.java:90)
01-15 16:20:37.511  8918  8918 W Bundle  : 	at com.goodfactory.wali.wali.onCreate(wali.java:54)
01-15 16:20:37.511  8918  8918 W Bundle  : 	at android.app.Activity.performCreate(Activity.java:7183)
01-15 16:20:37.511  8918  8918 W Bundle  : 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1220)
01-15 16:20:37.511  8918  8918 W Bundle  : 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2908)
01-15 16:20:37.511  8918  8918 W Bundle  : 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3030)
01-15 16:20:37.511  8918  8918 W Bundle  : 	at android.app.ActivityThread.-wrap11(Unknown Source:0)
01-15 16:20:37.511  8918  8918 W Bundle  : 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1696)
01-15 16:20:37.511  8918  8918 W Bundle  : 	at android.os.Handler.dispatchMessage(Handler.java:105)
01-15 16:20:37.511  8918  8918 W Bundle  : 	at android.os.Looper.loop(Looper.java:164)
01-15 16:20:37.511  8918  8918 W Bundle  : 	at android.app.ActivityThread.main(ActivityThread.java:6938)
01-15 16:20:37.511  8918  8918 W Bundle  : 	at java.lang.reflect.Method.invoke(Native Method)
01-15 16:20:37.511  8918  8918 W Bundle  : 	at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
01-15 16:20:37.511  8918  8918 W Bundle  : 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)
01-15 16:20:37.527  8918  9044 W zygote  : Skipping duplicate class check due to unrecognized classloader
01-15 16:20:37.534  8918  9044 I DynamiteModule: Considering local module com.google.android.gms.firebase_database:4 and remote module com.google.android.gms.firebase_database:6
01-15 16:20:37.534  8918  9044 I DynamiteModule: Selected remote version of com.google.android.gms.firebase_database, version >= 6
01-15 16:20:37.591  8918  9044 W zygote  : Skipping duplicate class check due to unrecognized classloader
01-15 16:20:37.631  8918  9099 D NetworkSecurityConfig: No Network Security Config specified, using platform default
01-15 16:20:37.640  8918  9099 D TcpOptimizer: TcpOptimizer-ON

01-15 16:20:37.751  8918  8930 I zygote  : Do partial code cache collection, code=51KB, data=41KB
01-15 16:20:37.752  8918  8930 I zygote  : After code cache collection, code=51KB, data=41KB
01-15 16:20:37.752  8918  8930 I zygote  : Increasing code cache capacity to 256KB
01-15 16:20:37.757  8918  8930 I zygote  : Compiler allocated 5MB to compile void android.widget.TextView.<init>(android.content.Context, android.util.AttributeSet, int, int)

01-15 16:20:37.827  8918  8918 I DynamiteModule: Considering local module com.google.android.gms.ads.dynamite:0 and remote module com.google.android.gms.ads.dynamite:11020
01-15 16:20:37.827  8918  8918 I DynamiteModule: Selected remote version of com.google.android.gms.ads.dynamite, version >= 11020
01-15 16:20:37.832  8918  8918 W zygote  : Skipping duplicate class check due to unrecognized classloader

01-15 16:20:37.847  8918  8918 D DynamitePackage: Instantiated singleton DynamitePackage.
01-15 16:20:37.847  8918  8918 D DynamitePackage: Instantiating com.google.android.gms.ads.ChimeraAdManagerCreatorImpl
01-15 16:20:37.871  8918  8930 I zygote  : Do full code cache collection, code=126KB, data=83KB
01-15 16:20:37.872  8918  8930 I zygote  : After code cache collection, code=105KB, data=67KB

01-15 16:20:37.928  8918  8918 I Ads     : Updating ad debug logging enablement.
01-15 16:20:37.937  8918  8918 I Ads     : Use AdRequest.Builder.addTestDevice("0E455563811A0F08A1FEB55A52CFA88D") to get test ads on this device.

01-15 16:20:37.951  8918  9201 W zygote  : Skipping duplicate class check due to unrecognized classloader

01-15 16:20:37.999  8918  9250 F libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0x7 in tid 9250 (Thread-4)
01-15 16:20:38.044  8918  9243 I DynamiteModule: Considering local module com.google.android.gms.ads.dynamite:0 and remote module com.google.android.gms.ads.dynamite:11020
01-15 16:20:38.044  8918  9243 I DynamiteModule: Selected remote version of com.google.android.gms.ads.dynamite, version >= 11020

01-15 16:20:38.093   971   971 I /system/bin/tombstoned: received crash request for pid 8918
01-15 16:20:38.094  9279  9279 I crash_dump32: performing dump of process 8918 (target tid = 9250)
01-15 16:20:38.094  9279  9279 F DEBUG   : pid: 8918, tid: 9250, name: Thread-4  >>> com.goodfactory.wali <<<

01-15 16:20:39.162   898   898 E audit   : type=1701 audit(1547580039.152:25672): auid=4294967295 uid=10571 gid=10571 ses=4294967295 subj=u:r:untrusted_app:s0:c512,c768 pid=8918 comm="Thread-4" exe="/system/bin/app_process32" sig=11

01-15 16:20:39.219  1629  1629 I Zygote  : Process 8918 exited due to signal (11)
01-15 16:20:39.222  1428  3838 I ActivityManager: Process com.goodfactory.wali (pid 8918) has died: vis  +99TOP (338,1747)

Process com.goodfactory.wali terminated.
```

**Comment by AndrewEQ** [comment]
Try this: https://github.com/fuse-open/uno/issues/129#issuecomment-443379570

**Comment by AndrewEQ** [comment]
Assuming you resolved this...
